---
abstract: 'sort lexically, but sort numeral parts numerically'
author:
  - 'Sean M. Burke <sburke@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.62, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Sort-Naturally
no_index:
  directory:
    - t
    - inc
requires:
  perl: 5
resources:
  repository: https://github.com/bingos/sort-naturally
version: 1.03
